name: deploy

on:
  push:
    branches:
      - master

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS v12
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install Dependencies
        run: yarn install
      - name: Check for syntax errors
        run: yarn build
